# Generated by Django 6.1.1 on 2026-09-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_code', models.CharField(max_length=50, unique=True)),
                ('weight_grams', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('TOO_LIGHT', 'Too Light')], max_length=20)),
                ('minutes_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='bins.bin')),
            ],
        ),
    ]
