# Generated by Django 6.1.1 on 2026-09-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=50, unique=True)),
                ('mac_address', models.CharField(max_length=17)),
                ('minutes_allocated', models.PositiveIntegerField(default=0)),
                ('time_remaining_sec', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('session_start', models.DateTimeField(blank=True, null=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wifi_sessions', to='deposits.deposit')),
            ],
        ),
    ]
