# Generated by Django 6.1.1 on 2026-09-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_code', models.CharField(max_length=50, unique=True)),
                ('location_name', models.CharField(max_length=150)),
                ('fill_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('FULL', 'Full')], default='READY', max_length=10)),
                ('last_emptied_at', models.DateTimeField(blank=True, null=True)),
                ('cumulative_waste_grams', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
