# Generated by Django 6.1.1 on 2026-09-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_deposit_grams', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('tier_one_max_grams', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('tier_one_multiplier', models.DecimalField(decimal_places=2, default=3, max_digits=10)),
                ('tier_two_max_grams', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('tier_two_base_minutes', models.PositiveIntegerField(default=60)),
                ('tier_two_multiplier', models.DecimalField(decimal_places=2, default=2, max_digits=10)),
                ('maximum_minutes_per_transaction', models.PositiveIntegerField(default=480)),
                ('session_expiry_hours', models.PositiveIntegerField(default=24)),
                ('bin_fill_alert_threshold', models.DecimalField(decimal_places=2, default=90, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
